src/api/models.py
from api import db
import datetime
from api.config import Config


date = datetime.date.today()


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')

    def __repr__(self):
        return f"User('{self.username}', '{self.image_file}')"


''' For now we are using dummy data but then we will get it from the video-chat or database. '''
interview_data = [
    {
        'interviewer': 'Epam Manager',
        'interviewee': 'Firstname Lastname',
        'agenda': 'Data Analyst position',
        'date_time': '{:%B %d, %Y}\n'.format(date),
        'image_source': '/static/default.jpg',
        'video_source': '/static/IMG_0909.MOV'
    }
]

src/api/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length


class Forms(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
    image = FileField('Your image', validators=[FileAllowed(['jpg', 'png', 'jpeg'])])
    submit = SubmitField('Upload')

src/api/__init__.py
from api.config import Config
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import MetaData
from sqlalchemy.orm import scoped_session, sessionmaker


db = SQLAlchemy()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    from api.routes import api_bp
    app.register_blueprint(api_bp)
    db.init_app(app)

    with app.app_context():
        db.create_all()
        session = scoped_session(sessionmaker())
        metadata = MetaData('sqlite:///face.db')
    return app

src/api/routes.py
from api import generator, db
from api.forms import Forms
from api.models import interview_data, User

from flask import Flask, render_template, Response, Blueprint, url_for, flash, redirect

api_bp = Blueprint('api_bp', __name__)


@api_bp.route('/')
def home():
    return render_template('home.html', interview_data=interview_data)


@api_bp.route('/about')
def about():
    return render_template('about.html')


@api_bp.route('/forms', methods=['GET', 'POST'])
def forms():
    form = Forms()
    if form.validate_on_submit():
        user = User(username=form.username.data)
        db.session.add(user)
        db.session.commit()
        flash(f'Info from {form.username.data} has been successfully received!', 'success')
        return redirect(url_for('api_bp.forms'))
    return render_template('forms.html', title='Forms', form=form)


@api_bp.route('/video_feed')
def video_feed():
    known_faces = []
    known_names = []
    return Response(generator.gen(known_faces, known_names),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

src/api/templates/about.html
{% extends 'layout.html' %}
{% block content %}
    <h1>About Page of our application!</h1>
    <p>Face detection during a video-chat.</p>
{% endblock content%}

src/api/templates/forms.html
{% extends 'layout.html' %}
{% block content %}
    <div class="content-section">
        <form  method="post">
            {{ form.hidden_tag() }}
            <fieldset class='form-group'>
                <legend class='border-bottom mb-4'>Upload your images for training</legend>
                <div class="form-group">
                    {{ form.username.label(class='form-control-label') }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.image.label() }}
                    {{ form.image(class="form-control-file") }}
                    {% if form.image.errors %}
                        {% for error in form.image.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info')}}
            </div>
        </form>
    </div>
{% endblock content%}

src/api/templates/home.html
{% extends 'layout.html' %}
{% block content %}
    {% for data in interview_data %}
        <div  class="content-section mt-4">
            <h4>Interview is conducted by {{ data.interviewer }}</h4>
            <p>The purpose of the meeting is {{ data.agenda }}</p>
            <img  class="embed-responsive embed-responsive-4by3" src="{{ url_for('api_bp.video_feed') }}">
        </div>
    {% endfor %}
{% endblock content%}

{% block candidate %}
    {% for data in interview_data %}
        <ul>
            <li>name: {{ data.interviewee }}</li>
            <li class="mb-4">date: {{ data.date_time }}</li>
            <li><img src="{{ data.image_source }}" alt="User Image" class="img-thumbnail"></li>
        </ul>
    {% endfor %}
{% endblock candidate%}

src/api/templates/layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
        <title>Face Detection</title>
    </head>
    <body>
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark  fixed-top  bg-steel">
              <div class="container">
                <a class="navbar-brand mr-4" href="/">Face Detection</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                  <div class="navbar-nav mr-auto">
                    <!-- <a class="nav-item nav-link" href="/">Feedabcks</a> -->
                    <a class="nav-item nav-link" href="{{ url_for('api_bp.about') }}">About</a>
                    <a class="nav-item nav-link" href="{{ url_for('api_bp.forms') }}">Forms</a>
                  </div>
                  <!-- Navbar Right Side -->
                  <div class="navbar-nav">
                    <a class="nav-item nav-link" href="/login">Login</a>
                    <a class="nav-item nav-link" href="/register">Register</a>
                  </div>
                </div>
              </div>
            </nav>
        </header>

        <main role="main" class="container">
          <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                  {% if messages %}
                    {% for category, message in messages %}
                      <div class="alert alert-{{ category }}">
                        {{ message }}
                      </div>
                    {% endfor %}
                  {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
              <div class="content-section mt-4">
                <h3>About the candidate.</h3>
                <p class='text-muted'>
                {% block candidate %}{% endblock %}
                </p>
              </div>
            </div>
          </div>
        </main>


        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>